vich_uploader:
    db_driver: orm

    mappings:
       photo:
           uri_prefix: '/img/post_images/'
           upload_destination: '%kernel.project_dir%/public/img'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false

